name: Build

on:
  pull_request: {}
  push:
    branches:
    - swaps-qa-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo "::set-output name=NVMRC::$(cat ./.nvmrc)"
      id: nvm
    - name: Use Node + Yarn
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "yarn"
    - run: yarn install --frozen-lockfile
    - name: Build artifacts for verification
      if: github.ref != 'refs/heads/main'
      run: yarn build
      env:
        ALCHEMY_KEY: ${{ secrets.DEV_ALCHEMY_API_KEY }}
        BLOCKNATIVE_API_KEY: ${{ secrets.DEV_BLOCKNATIVE_API_KEY }}
    - name: Build artifacts for upload
      if: github.ref == 'refs/heads/swaps-qa-build'
      run: yarn build
      env:
        ALCHEMY_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        BLOCKNATIVE_API_KEY: ${{ secrets.BLOCKNATIVE_API_KEY }}
    - name: Upload build on swaps-qa-build
      if: github.ref == 'refs/heads/swaps-qa-build'
      uses: actions/upload-artifact@v2
      with:
        name: extension-builds
        path: dist/*.zip
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo "::set-output name=NVMRC::$(cat ./.nvmrc)"
      id: nvm
    - name: Use Node + Yarn
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "yarn"
    - run: yarn install --frozen-lockfile
    - run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo "::set-output name=NVMRC::$(cat ./.nvmrc)"
      id: nvm
    - name: Use Node + Yarn
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "yarn"
    - run: yarn install --frozen-lockfile
    - run: yarn lint
